# Generated by Django 5.0.7 on 2024-07-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sec_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='sec_user',
        ),
        migrations.CreateModel(
            name='sec_user_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sec_group')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sec_user')),
            ],
        ),
    ]
