# Generated by Django 5.0.7 on 2024-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sec_group_rename_usuarios_sec_user_sec_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sec_group',
            name='group_id',
            field=models.CharField(max_length=100),
        ),
    ]
