# Generated by Django 5.0.7 on 2024-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
